version: '3.8'

services:
  backend:
    image: 559050249664.dkr.ecr.ap-northeast-2.amazonaws.com/donjjul-backend:latest
    ports:
      - "80:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      DB_HOST: spring-db.czuosc4sm6fc.ap-northeast-2.rds.amazonaws.com
      DB_PORT: 3306
      DB_NAME: donjjul
      DB_USERNAME: admin
      DB_PASSWORD: ossprojdonjjul
      OCR_SERVER_URL: http://ocr:5000
    depends_on:
      - ocr

  ocr:
    image: 559050249664.dkr.ecr.ap-northeast-2.amazonaws.com/donjjul-ocr:latest
    ports:
      - "5000:5000"
