version: '3'
services:
  mysql:
    image: mysql:8.0
    container_name: donjjul-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: goodpassword
      MYSQL_DATABASE: donjjul
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
