spring:
  config:
    activate:
      on-profile: dev

spring:
  datasource:
    url: jdbc:mysql://<호스트>:3306/donjjul?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
    username: root
    password: goodpassword
    driver-class-name: com.mysql.cj.jdbc.Driver

  ocr:
    url: http://localhost:5000/ocr

server:
  port: 8080
