# src/backend/src/main/resources/application.yml

spring:
  profiles:
    active: docker

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  address:0.0.0.0
  port: 8080

security:
  filter:
    dispatchers: request

jwt:
  secret: donjjul-secret-key-that-opens-every-door-there-is

ocr:
  url: "http://ocr:5000"