# netlify.toml

[build]
base = "src/frontend"
command = "npm ci && npm run build"
publish = ".next"


[build.environment]
NODE_ENV = "production"
NEXT_PUBLIC_API_URL = "http://13.125.255.84"

[[plugins]]
package = "@netlify/plugin-nextjs"


