# netlify.toml

[build]
base = "src/frontend"
command = "npm install && npm install --save-dev typescript@latest @types/node@latest && npm run build"
publish = ".next"


[build.environment]
NODE_ENV = "production"
NEXT_PUBLIC_API_URL = "https://dummy.example.com"

[[plugins]]
package = "@netlify/plugin-nextjs"

